/**
 * Stores the Yarn Application Original Info.
 */
CREATE TABLE IF NOT EXISTS `yarn_app_original` (
  `app_id` varchar(50) NOT NULL COMMENT 'The application id, e.g., application_1236543456321_1234567',
  `name` varchar(1024) NOT NULL COMMENT 'The application name',
  `queue_name` varchar(150) DEFAULT NULL COMMENT 'The queue the application was submitted to',
  `user` varchar(50) NOT NULL COMMENT 'The user who started the application',
  `state` varchar(20) NOT NULL,
  `final_status` varchar(20) NOT NULL,
  `application_type` varchar(20) NOT NULL COMMENT 'The Job Type e.g, SPARK, MAPREDUCE',
  `application_tags` varchar(100) DEFAULT NULL,
  `tracking_url` varchar(255) DEFAULT NULL COMMENT 'The web URL that can be used to track the application',
  `start_time` bigint(20) unsigned NOT NULL COMMENT 'The time in which application started',
  `finish_time` bigint(20) unsigned NOT NULL COMMENT 'The time in which application finished',
  `elapsed_time` bigint(20) unsigned DEFAULT NULL,
  `memory_seconds` bigint(20) unsigned DEFAULT '0' COMMENT 'The Memory resources used by the job in MB Seconds',
  `vcore_seconds` bigint(20) unsigned DEFAULT '0' COMMENT 'The CPU resources used by the job in core Seconds',
  `diagnostics` text,
  `cluster_name` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`app_id`),
  KEY `yarn_app_original_i1` (`finish_time`),
  KEY `yarn_app_original_i2` (`user`,`finish_time`),
  KEY `yarn_app_original_i3` (`application_type`,`user`,`finish_time`),
  KEY `yarn_app_original_i7` (`start_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `spark_app` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `app_id` varchar(100) NOT NULL DEFAULT '',
  `app_name` varchar(500) NOT NULL DEFAULT '',
  `attempt_id` varchar(20) NOT NULL DEFAULT '',
  `queue` varchar(100) NOT NULL DEFAULT '',
  `tracking_url` varchar(500) NOT NULL DEFAULT '',
  `user` varchar(100) NOT NULL DEFAULT '',
  `spark_user` varchar(100) NOT NULL DEFAULT '',
  `vcore_seconds` bigint(20) DEFAULT NULL,
  `memory_seconds` bigint(20) DEFAULT NULL,
  `start_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `end_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `status` varchar(100) NOT NULL DEFAULT '',
  `view_acls` varchar(500) NOT NULL DEFAULT '',
  `admin_acls_groups` varchar(500) NOT NULL DEFAULT '',
  `cluster` varchar(150) NOT NULL DEFAULT '',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`update_time`),
  KEY `idx_appid` (`app_id`),
  KEY `idx_start_time` (`start_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `spark_env` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `app_id` varchar(100) NOT NULL DEFAULT '',
  `jvm_info` mediumtext,
  `spark_props` mediumtext,
  `sys_props` mediumtext,
  `class_path` mediumtext,
  `cluster` varchar(150) NOT NULL DEFAULT '',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`update_time`),
  UNIQUE KEY `appid` (`app_id`,`update_time`),
  KEY `idx_appid` (`app_id`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `spark_executor` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `app_id` varchar(100) NOT NULL DEFAULT '',
  `executor_id` varchar(100) NOT NULL DEFAULT '',
  `host_port` varchar(100) NOT NULL DEFAULT '',
  `rdd_blocks` bigint(20) DEFAULT NULL,
  `mem_used` bigint(20) DEFAULT NULL,
  `max_mem` bigint(20) DEFAULT NULL,
  `disk_used` bigint(20) DEFAULT NULL,
  `completed_tasks` bigint(20) DEFAULT NULL,
  `failed_tasks` bigint(20) DEFAULT NULL,
  `total_tasks` bigint(20) DEFAULT NULL,
  `duration` bigint(20) DEFAULT NULL,
  `input_bytes` bigint(20) DEFAULT NULL,
  `output_bytes` bigint(20) DEFAULT NULL,
  `shuffle_read` bigint(20) DEFAULT NULL,
  `shuffle_write` bigint(20) DEFAULT NULL,
  `input_record` bigint(20) DEFAULT NULL,
  `output_record` bigint(20) DEFAULT NULL,
  `stdout` varchar(200) NOT NULL DEFAULT '',
  `stderr` varchar(200) NOT NULL DEFAULT '',
  `start_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `finish_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `finish_reason` varchar(50) NOT NULL DEFAULT '',
  `cluster` varchar(150) NOT NULL DEFAULT '',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`update_time`),
  KEY `idx_executorid` (`executor_id`),
  KEY `idx_appid` (`app_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `spark_job` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `app_id` varchar(100) NOT NULL DEFAULT '',
  `job_id` int(11) NOT NULL DEFAULT '-1',
  `job_group` varchar(50) DEFAULT '',
  `stage_ids` varchar(50) DEFAULT '',
  `submission_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `completed_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `status` varchar(50) DEFAULT '',
  `error` text,
  `failed_stage_ids` varchar(200) NOT NULL DEFAULT '',
  `num_tasks` int(11) NOT NULL DEFAULT '-1',
  `num_active_tasks` int(11) NOT NULL DEFAULT '-1',
  `num_completed_tasks` int(11) NOT NULL DEFAULT '-1',
  `num_skipped_tasks` int(11) NOT NULL DEFAULT '-1',
  `num_failed_tasks` int(11) NOT NULL DEFAULT '-1',
  `num_killed_tasks` int(11) NOT NULL DEFAULT '-1',
  `task_failure_rate` double(8,6) NOT NULL DEFAULT '0.000000',
  `num_active_stages` int(11) NOT NULL DEFAULT '-1',
  `num_skipped_stages` int(11) NOT NULL DEFAULT '-1',
  `num_failed_stages` int(11) NOT NULL DEFAULT '-1',
  `cluster` varchar(150) NOT NULL DEFAULT '',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`update_time`),
  KEY `idx_jobid` (`job_id`),
  KEY `idx_appid` (`app_id`),
  KEY `idx_submission_time` (`submission_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `spark_stage` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `app_id` varchar(100) NOT NULL DEFAULT '',
  `job_id` int(11) NOT NULL DEFAULT '-1',
  `stage_id` int(11) NOT NULL DEFAULT '-1',
  `attempt_id` int(11) NOT NULL DEFAULT '-1',
  `name` varchar(200) NOT NULL DEFAULT '',
  `parent_stage_id` varchar(200) NOT NULL DEFAULT '',
  `description` text,
  `accumulables` text,
  `status` varchar(20) NOT NULL DEFAULT '',
  `failure_reason` text,
  `num_active_tasks` int(11) NOT NULL DEFAULT '-1',
  `num_killed_tasks` int(11) NOT NULL DEFAULT '-1',
  `num_complete_tasks` int(11) NOT NULL DEFAULT '-1',
  `num_failed_tasks` int(11) NOT NULL DEFAULT '-1',
  `executor_run_time` bigint(20) NOT NULL DEFAULT '-1',
  `executor_cpu_time` bigint(20) NOT NULL DEFAULT '-1',
  `duration` bigint(20) NOT NULL DEFAULT '-1',
  `input_bytes` bigint(20) NOT NULL DEFAULT '-1',
  `input_records` bigint(20) NOT NULL DEFAULT '-1',
  `output_bytes` bigint(20) NOT NULL DEFAULT '-1',
  `output_records` bigint(20) NOT NULL DEFAULT '-1',
  `shuffle_read_bytes` bigint(20) NOT NULL DEFAULT '-1',
  `shuffle_read_records` bigint(20) NOT NULL DEFAULT '-1',
  `shuffle_write_bytes` bigint(20) NOT NULL DEFAULT '-1',
  `shuffle_write_records` bigint(20) NOT NULL DEFAULT '-1',
  `memory_bytes_spilled` bigint(20) NOT NULL DEFAULT '-1',
  `disk_bytes_spilled` bigint(20) NOT NULL DEFAULT '-1',
  `cluster` varchar(150) NOT NULL DEFAULT '',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`update_time`),
  UNIQUE KEY `stage_id` (`app_id`,`stage_id`,`update_time`),
  KEY `idx_stageid` (`stage_id`),
  KEY `idx_appid` (`app_id`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `spark_storage` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `app_id` varchar(100) NOT NULL DEFAULT '',
  `executor_id` varchar(100) NOT NULL DEFAULT '',
  `host` varchar(100) NOT NULL DEFAULT '',
  `port` int(11) NOT NULL DEFAULT '-1',
  `blkmngr_id` varchar(100) NOT NULL DEFAULT '',
  `max_memory` bigint(20) NOT NULL DEFAULT '-1',
  `cache_size` bigint(20) NOT NULL DEFAULT '-1',
  `disk_used` bigint(20) NOT NULL DEFAULT '-1',
  `mem_used` bigint(20) NOT NULL DEFAULT '-1',
  `mem_remaining` bigint(20) NOT NULL DEFAULT '-1',
  `num_blocks` int(11) NOT NULL DEFAULT '-1',
  `num_rdd_blocks` int(11) NOT NULL DEFAULT '-1',
  `cluster` varchar(150) NOT NULL DEFAULT '',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `spark_task` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `app_id` varchar(100) NOT NULL DEFAULT '',
  `job_id` int(11) NOT NULL DEFAULT '-1',
  `stage_id` int(11) NOT NULL DEFAULT '-1',
  `executor_id` varchar(100) NOT NULL DEFAULT '',
  `task_id` bigint(20) NOT NULL DEFAULT '0',
  `attempt_id` int(11) NOT NULL DEFAULT '-1',
  `launch_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `finish_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `duration` bigint(20) NOT NULL DEFAULT '0',
  `getting_result_time` bigint(20) NOT NULL DEFAULT '0',
  `status` varchar(100) NOT NULL DEFAULT '',
  `accumulables` varchar(100) NOT NULL DEFAULT '',
  `host` varchar(100) NOT NULL DEFAULT '',
  `locality` varchar(100) NOT NULL DEFAULT '',
  `error_message` text,
  `executor_deser_time` bigint(20) NOT NULL DEFAULT '0',
  `executor_deser_cpu_time` bigint(20) NOT NULL DEFAULT '0',
  `executor_run_time` bigint(20) NOT NULL DEFAULT '0',
  `executor_cpu_time` bigint(20) NOT NULL DEFAULT '0',
  `result_size` bigint(20) NOT NULL DEFAULT '0',
  `jvm_gc_time` bigint(20) NOT NULL DEFAULT '0',
  `result_serial_time` bigint(20) NOT NULL DEFAULT '0',
  `memory_bytes_spilled` bigint(20) NOT NULL DEFAULT '0',
  `disk_bytes_spilled` bigint(20) NOT NULL DEFAULT '0',
  `peak_execution_memory` bigint(20) NOT NULL DEFAULT '0',
  `input_bytes_read` bigint(20) NOT NULL DEFAULT '0',
  `input_record_read` bigint(20) NOT NULL DEFAULT '0',
  `output_bytes_written` bigint(20) NOT NULL DEFAULT '0',
  `output_records_written` bigint(20) NOT NULL DEFAULT '0',
  `shuffle_remote_blocks_fetched` bigint(20) NOT NULL DEFAULT '0',
  `shuffle_local_blocks_fetched` bigint(20) NOT NULL DEFAULT '0',
  `shuffle_remote_bytes_read` bigint(20) NOT NULL DEFAULT '0',
  `shuffle_local_bytes_read` bigint(20) NOT NULL DEFAULT '0',
  `shuffle_fetch_wait_time` bigint(20) NOT NULL DEFAULT '0',
  `shuffle_records_read` bigint(20) NOT NULL DEFAULT '0',
  `shuffle_bytes_written` bigint(20) NOT NULL DEFAULT '0',
  `shuffle_records_written` bigint(20) NOT NULL DEFAULT '0',
  `shuffle_write_time` bigint(20) NOT NULL DEFAULT '0',
  `cluster` varchar(150) NOT NULL DEFAULT '',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`update_time`),
  UNIQUE KEY `task_id` (`app_id`,`task_id`,`attempt_id`,`update_time`),
  KEY `idx_appid` (`app_id`),
  KEY `idx_stageid` (`stage_id`),
  KEY `idx_host` (`host`),
  KEY `idx_launch_time` (`launch_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;